# This is a basic workflow to help you get started with Actions

name: Create Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

      - uses: rickstaa/action-create-tag@v1
        #if: steps.check.outputs.changed == 'true'
        with:
          tag: "v${{ steps.check.outputs.version }}"
          
      - name: Create Release
        #if: steps.check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPOS_TOKEN }}
        with:
          tag_name: "v${{ steps.check.outputs.version }}"
          release_name: "Release v${{ steps.check.outputs.version }}"
          body: "${{ github.event.head_commit.message }}"
          draft: false
          prerelease: false
